#!/bin/bash
echo "Logging in to Docker as $DOCKER_USERNAME"
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
case "$1" in
    master )
        echo "Nothing to do yet" ;;
        
    edge )
        echo "Tagging and pushing images as edge"
        docker build -t philhawthorne/ha-dockermon:edge .
        docker push philhawthorne/ha-dockermon:edge
        ;;
    esac