#!/bin/bash
echo "Logging in to Docker as $DOCKER_USERNAME"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
case "$1" in
    master )
        echo "Nothing to do yet" ;;
        
    edge )
        echo "Tagging and pushing images as edge"
        docker build -t philhawthorne/ha-dockermon:edge .
        # prepare qemu
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build -t philhawthorne/ha-dockermon:edge-arm -f Dockerfile.RaspberryPi .
        docker push philhawthorne/ha-dockermon:edge
        docker push philhawthorne/ha-dockermon:edge-arm
        ;;
    esac