#!/bin/bash
echo "Logging in to Docker as $DOCKER_USERNAME"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
case "$1" in
    master )
        docker build -t philhawthorne/ha-dockermon:latest .
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build -t philhawthorne/ha-dockermon:arm -f Dockerfile.RaspberryPi .
        docker push philhawthorne/ha-dockermon:latest
        docker push philhawthorne/ha-dockermon:arm
        ;;
    edge )
        echo "Tagging and pushing images as edge"
        docker build -t philhawthorne/ha-dockermon:edge .
        # prepare qemu
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build -t philhawthorne/ha-dockermon:edge-arm -f Dockerfile.RaspberryPi .
        docker push philhawthorne/ha-dockermon:edge
        docker push philhawthorne/ha-dockermon:edge-arm
        ;;
    *)
        echo "Tagging release $1"
        docker build -t philhawthorne/ha-dockermon:"$1" .
        # prepare qemu
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build -t philhawthorne/ha-dockermon:"$1"-arm -f Dockerfile.RaspberryPi .
        docker push philhawthorne/ha-dockermon:"$1"
        docker push philhawthorne/ha-dockermon:"$1"-arm
        ;;
    esac