FROM resin/rpi-raspbian
ENV config_dir=/config
#Install NodeJS
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
RUN mkdir -p /usr/src/app && mkdir /config
WORKDIR /usr/src/app

COPY package.json /usr/src/app
RUN npm install

COPY default_settings.json /usr/src/app
COPY index.js /usr/src/app
CMD npm start
